[Registry]
ServerAddr = "127.0.0.1"
#ConsulAddr = "192.168.213.193:8500"
HealthCheckAddr = "192.168.213.193:47015"
#HealthCheckInterval = 1
#HealthCheckTimeOut = 1
#ConsulTags = ["qjk","jinkun", "123", "test", "test1"]
#WaitTime = 5
#PrometheusNameSpace = "qjk"