// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: a2b01cac16
// Version Date: Thu Oct 20 18:44:52 UTC 2022

package main

import (
	"flag"

	// This Service
	"github.com/jkprj/jkfr/protobuf/demo/hello-service/handlers"
	"github.com/jkprj/jkfr/protobuf/demo/hello-service/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	cfg := server.DefaultConfig
	cfg = handlers.SetConfig(cfg)

	server.Run(cfg)
}
